import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';
import { Header } from './(components)/Header';
import { Main } from './(components)/Main';
import { Footer } from './(components)/Footer';
import { ModalProvider } from '@/components/Modal';
import { Modal } from '@/components/Modal';
import { DisclaimerModal } from './(components)/DisclaimerModal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ModalProvider>
        <body className={clsx(inter.className, 'flex min-h-screen flex-col px-4 pb-4 md:px-8')}>
          <Header />
          <Main>{children}</Main>
          <Footer />
          <DisclaimerModal />
        </body>
      </ModalProvider>
    </html>
  );
}
